version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    user: ${DB_USER}
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
